0-module-1st-task
js-tasks-ru/jsbasic-20210420_dzitiev pull request #1
Opened 2021-04-27 16:20 UTC by alexdzitiev

2021-04-27 16:20 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-04-27 19:20 UTC, SinimaWath requested changes

2021-04-27 19:20 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  return factorial;
Как-то слишком сложно написано (

В javascript есть цикл while.

Также всегда принято писать скобки, для разделения логических блоков:
```

while (...) {
  
}
```

2021-04-27 21:46 UTC, alexdzitiev commented
Спасибо, учту

вт, 27 апр. 2021 г., 22:20 Vladik Tarasov ***@***.***>:

> *@SinimaWath* requested changes on this pull request.
> ------------------------------
>
> In 1-module/1-task/index.js
> <https://github.com/js-tasks-ru/jsbasic-20210420_dzitiev/pull/1#discussion_r621524677>
> :
>
> > +  let factorial = 1;
>
> +  for (; n!=0 ;)
>
> +  factorial *=n-- ;
>
> +  return factorial;
>
>
> Как-то слишком сложно написано (
>
> В javascript есть цикл while.
>
> Также всегда принято писать скобки, для разделения логических блоков:
>
>
>
> while (...) {
>
>
>
> }
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/js-tasks-ru/jsbasic-20210420_dzitiev/pull/1#pullrequestreview-646266024>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APTQKKLJA6TFXIVVSLHA2HLTK4E7NANCNFSM43VKF7TA>
> .
>

2021-05-01 14:36 UTC, SinimaWath approved these changes

2021-05-01 14:36 UTC, merged